function migrateProject(s){
 if(!s||s.schemaVersion!==1)return s;
 if(!Array.isArray(s.tasks))throw Error('Missing quests in backup');
 const defaults=window.NIGHTSHIFT_SEED;
 for(const t of s.tasks){const template=defaults.tasks.find(x=>x.id===t.id);Object.assign(t,{brief:t.brief??template?.brief??'Describe the purpose and the next concrete action.',completion:t.completion??template?.completion??t.context??'',dayId:'',offset:0,locationId:'',equipmentIds:[],sceneIds:[],budgetIds:[],requireDayReady:false});if(template&&t.checklist?.length===0&&!['Done','Not applicable'].includes(t.status))t.checklist=JSON.parse(JSON.stringify(template.checklist));if(['G01','N05','E08'].includes(t.id)&&template){t.deps=[...new Set([...t.deps,...template.deps])];if(t.status==='Done')t.review=true;}}
 for(const t of defaults.tasks)if(!s.tasks.some(x=>x.id===t.id)&&(/^(X|CALL-)/.test(t.id)))s.tasks.push(JSON.parse(JSON.stringify(t)));
 for(const key of ['days','scenes','budget','props','vfx'])s[key]=JSON.parse(JSON.stringify(defaults[key]));
 s.settings.budgetCap=1500;s.schemaVersion=2;return s;
}
function validateProduction(s){
 for(const key of ['days','scenes','budget','props','vfx']){if(!Array.isArray(s[key])||s[key].length>5000)throw Error('Invalid '+key);const ids=new Set();for(const r of s[key]){if(!r||typeof r.id!=='string'||ids.has(r.id)||typeof r.name!=='string')throw Error('Invalid '+key+' record');ids.add(r.id);}}
 const ref=(key,id)=>!id||s[key].some(x=>x.id===id);const refs=(key,ids)=>Array.isArray(ids)&&ids.every(id=>typeof id==='string'&&ref(key,id));
 if(typeof s.settings.budgetCap!=='number'||!Number.isFinite(s.settings.budgetCap)||s.settings.budgetCap<0)throw Error('Invalid budget ceiling');
 for(const key of ['props','vfx'])for(const r of s[key]){if(!ref('scenes',r.sceneId)||!validDate(r.due))throw Error('Invalid asset scene or date');for(const v of Object.values(r))if(typeof v!=='string')throw Error('Invalid asset field');}
 for(const t of s.tasks){if(typeof t.brief!=='string'||typeof t.completion!=='string'||!Number.isInteger(t.offset)||typeof t.requireDayReady!=='boolean'||!ref('days',t.dayId)||!ref('locations',t.locationId)||!refs('equipment',t.equipmentIds)||!refs('scenes',t.sceneIds)||!refs('budget',t.budgetIds))throw Error('Invalid quest links: '+t.id);}
 for(const d of s.days){if(!validDate(d.date)||!['Proposed','Confirmed','Completed','Cancelled'].includes(d.status)||!ref('locations',d.locationId)||typeof d.accessConfirmed!=='boolean'||!Number.isFinite(d.capacity)||d.capacity<=0||!Number.isFinite(d.reserve)||d.reserve<0||!Array.isArray(d.assignments)||!refs('equipment',d.equipmentIds))throw Error('Invalid shoot day');const people=new Set();for(const a of d.assignments){if(!a.personId||!ref('people',a.personId)||people.has(a.personId)||!['Unknown','Tentative','Available','Unavailable'].includes(a.availability)||typeof a.role!=='string'||typeof a.call!=='string'||!validDate(a.forDate))throw Error('Invalid day assignment');people.add(a.personId);}}
 for(const s1 of s.scenes)if(!ref('days',s1.dayId)||!Array.isArray(s1.cast)||s1.cast.some(x=>typeof x!=='string')||!Number.isFinite(s1.hours)||s1.hours<0||typeof s1.set!=='string'||typeof s1.notes!=='string')throw Error('Invalid scene');
 for(const b of s.budget){if(!['Cash','In-kind'].includes(b.kind))throw Error('Invalid budget kind');for(const k of ['estimate','committed','actual'])if(b[k]!==null&&(!Number.isFinite(b[k])||b[k]<0))throw Error('Budget values must be blank or nonnegative numbers');}
 return s;
}
function taskDue(t){if(!t.dayId)return t.due;const d=state.days.find(d=>d.id===t.dayId);if(!d?.date)return '';return new Date(Date.parse(d.date+'T12:00:00Z')+t.offset*86400000).toISOString().slice(0,10)}
function urgency(t){if(satisfied(t))return {level:'complete',label:t.status==='Not applicable'?'Excluded':'Complete'};const due=taskDue(t);if(!due)return {level:'open',label:'Date open'};const n=Math.round((Date.parse(due+'T12:00:00Z')-Date.parse(today()+'T12:00:00Z'))/86400000);return {level:n<=2?'red':n<=7?'orange':n<=14?'yellow':'green',label:n<0?`${-n}d overdue`:n===0?'Due today':`Due in ${n}d`};}
function dayHours(d){return state.scenes.filter(s=>s.dayId===d.id).reduce((n,s)=>n+s.hours,0)+d.reserve;}
function dayIssues(d){const out=[];if(!d.date)out.push('Shoot date open');if(d.status==='Cancelled')out.push('Day cancelled');if(!d.locationId)out.push('Location not assigned');else {const loc=state.locations.find(l=>l.id===d.locationId);if(loc.status!=='Confirmed')out.push('Location not confirmed');}if(!d.accessConfirmed)out.push('Date-specific access unconfirmed');if(dayHours(d)>d.capacity)out.push(`Scene load ${dayHours(d)}h exceeds ${d.capacity}h capacity`);if(!state.scenes.some(s=>s.dayId===d.id))out.push('No scenes assigned');
 for(const role of ['Director','DoP','Sound'])if(!d.assignments.some(a=>a.role.toLowerCase().split(',').map(x=>x.trim()).includes(role.toLowerCase())))out.push(`${role} not assigned`);
 for(const character of new Set(state.scenes.filter(s=>s.dayId===d.id).flatMap(s=>s.cast)))if(!d.assignments.some(a=>a.role.split(',').map(x=>x.trim().toLowerCase()).includes(character.toLowerCase())))out.push(`Cast: ${character} not assigned`);
 for(const a of d.assignments){const p=state.people.find(p=>p.id===a.personId);if(p.commitment!=='Confirmed')out.push(`${p.name}: role not confirmed`);if(!d.date||a.forDate!==d.date||a.availability!=='Available')out.push(`${p.name}: ${a.forDate!==d.date?'reconfirm date':a.availability.toLowerCase()}`);if(!a.call)out.push(`${p.name}: call time open`);if(d.date&&state.days.some(other=>other.id!==d.id&&other.date===d.date&&!['Cancelled','Completed'].includes(other.status)&&other.assignments.some(x=>x.personId===a.personId)))out.push(`${p.name}: assigned to another day on this date`);}
 for(const id of d.equipmentIds){const e=state.equipment.find(x=>x.id===id);if(!['Confirmed','Collected'].includes(e.status))out.push(`Equipment: ${e.name} not ready`);}return out;}
function resourceBlockers(t){const out=[];if(t.requireDayReady){const d=state.days.find(d=>d.id===t.dayId);if(!d)out.push('Link a shoot day');else{if(!['Confirmed','Completed'].includes(d.status))out.push('Shoot day is not confirmed');out.push(...dayIssues(d));}}if(t.locationId&&state.locations.find(l=>l.id===t.locationId)?.status!=='Confirmed')out.push('Linked location is not confirmed');for(const id of t.equipmentIds){const e=state.equipment.find(x=>x.id===id);if(!['Confirmed','Collected','Returned'].includes(e.status))out.push('Linked equipment not confirmed: '+e.name);}return out;}
function touchLinked(kind,id){for(const t of state.tasks){const linked=kind==='days'?t.dayId===id:kind==='locations'?t.locationId===id:kind==='equipment'?t.equipmentIds.includes(id):kind==='scenes'?t.sceneIds.includes(id):kind==='budget'?t.budgetIds.includes(id):t.personId===id;if(linked){if(t.status==='Done')t.review=true;invalidate(t.id);}}}
function budgetTotals(){const cash=state.budget.filter(b=>b.kind==='Cash');const sum=k=>cash.reduce((n,b)=>n+(b[k]??0),0);const exposure=cash.reduce((n,b)=>n+Math.max(b.estimate??0,b.committed??0,b.actual??0),0);return {estimate:sum('estimate'),committed:sum('committed'),actual:sum('actual'),exposure,remaining:state.settings.budgetCap-exposure,unknown:cash.filter(b=>b.estimate===null&&b.committed===null&&b.actual===null).length};}
